### ISSUE TITLE
Show upcoming earnings

### ISSUE THREAD

**Issue by kacasey8** [Fortisque/option_wheel_tracker#33]
I think it would be really useful to see if an option includes an earnings before you go for it. Especially on puts you might be surprised by taking a 2 week put, and then that includes an earnings call.

**Comment by rcaseyatbat** [comment]
I couldn't figure out an easy way to use the user-entered Expiration Date in the template, so I added color coded alerts:
Red - Earnings is before the default exp date (next friday)
Yellow - Earnings within 14 days from now (or unknown earnings date)
Green - Earnings > 14 days away
